name: Create Release on Addons Change

on:
  push:
    paths:
      - 'addons/**'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Extract version from plugin.cfg
    - name: Extract version from plugin.cfg
      id: extract_version
      run: |
        VERSION=$(grep '^version=' addons/godot_matrix_sdk/plugin.cfg | cut -d'=' -f2 | tr -d '"' | tr -d '[:space:]')
        echo "VERSION=$VERSION"
        echo "::set-output name=version::$VERSION"

    # Create the ZIP file
    - name: Create ZIP file
      run: |
        VERSION=${{ steps.extract_version.outputs.version }}
        zip -r "godot-matrix-sdk-${VERSION}.zip" addons

    # Create a release on GitHub
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.extract_version.outputs.version }}
        release_name: "Godot Matrix SDK v${{ steps.extract_version.outputs.version }}"
        draft: false
        prerelease: false

    # Upload the ZIP file to the release
    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "./godot-matrix-sdk-${{ steps.extract_version.outputs.version }}.zip"
        asset_name: "godot-matrix-sdk-${{ steps.extract_version.outputs.version }}.zip"
        asset_content_type: application/zip
